### ISSUE TITLE
Themes

### ISSUE THREAD

**Issue by jxnblk** [jxnblk/mdx-go#4]

**Comment by panr** [comment]
Hi @jxnblk, I spotted an issue with theming. When you want to create a dark theme or something that hasn't `white` background you will get:

<img width="1792" alt="rootbackground" src="https://user-images.githubusercontent.com/1303365/44676982-0b0a1980-aa35-11e8-9c07-17ec90ede41d.png">

It's because `Root` component has no access to this theme background variables out of box without changing anything in layout.

I wrapped elements in the same way as you did with the base theme:

<img width="302" alt="zrzut ekranu 2018-08-27 o 20 14 11" src="https://user-images.githubusercontent.com/1303365/44677393-17db3d00-aa36-11e8-92c3-89eafaf62da8.png">

Am I doing something wrong? 🤔

**Comment by jxnblk** [comment]
Just FYI, this issue was meant as a placeholder for some things in mdx-themes.

But looks like there's at least two options with what you're trying to do:

1. Make the container for your Root component have `min-width: 100vh`
2. Use the `<Head />` component and add a `<style>` tag with CSS that applies colors to the `<body>` element (this *should* work within the Root component, but I haven't tried it out)

**Comment by panr** [comment]
> Just FYI, this issue was meant as a placeholder for some things in mdx-themes
Sorry, I didn't know that 😭 I thought my issue was related to that.

So, adding container for `Root` with additional styling works of course, but I thought it wasn't necessary and providing new theme without changing the layout should be enough. Especially when you could import some random theme in the future.

So if I messed up this issue placeholder you can close and reopen it. Sorry again 😉

**Comment by jxnblk** [comment]
No worries! Just wanted to set expectations for what the issue title meant is all – "theming" in mdx-go so far only means wrapping the content with a component, that might happen to handle some CSS/theming related things, so essentially it uses the same mechanism as a "layout" if that makes any sense
